services:
  - type: web
    name: sunrise-school
    runtime: docker
    plan: free
    region: oregon
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 80
